# Gradle
org.gradle.jvmargs=-Xmx5G
org.gradle.daemon=false

# Project
modVersion=3.3.6
javaVersion=25

# Common
minecraftVersion=26.2
thisNeoFormVersion=26.2-1

# Fabric
fabricApiVersion=0.152.1
fabricLoaderVersion=0.19.3
fabricMinecraftVersionRange=>=26.2

# NeoForge
neoforgeVersion=26.2.0.1-beta
neoforgeMinecraftVersionRange=[26.2,26.3)
