# Gradle
org.gradle.jvmargs=-Xmx5G
org.gradle.daemon=false

# Project
modVersion=3.3.6
javaVersion=25

# Common
minecraftVersion=26.3

# Fabric
fabricApiVersion=0.160.5
fabricLoaderVersion=0.19.5
fabricMinecraftVersionRange=>=26.3

# NeoForge
neoforgeVersion=26.3.0.3-beta
neoforgeMinecraftVersionRange=[26.3,26.4)
