---
name: Build
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "temurin"
          cache: "gradle"

      - name: Give permissions to Gradle
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew export

      - name: Upload a Java 17 artifact
        uses: actions/upload-artifact@v4
        with:
          name: PacketFixerFabric
          path: fabric/build/libs/**.jar

      - name: Upload a Java 21 artifact
        uses: actions/upload-artifact@v4
        with:
          name: PacketFixerNeoForge
          path: neoforge/build/libs/**.jar
